# Generated by Django 6.0.7 on 2026-07-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=50)),
                ('cpu_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('upload_bytes', models.BigIntegerField()),
                ('download_bytes', models.BigIntegerField()),
                ('status', models.CharField(default='Online', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
